version: '3.8'

services:
  code-server:
    image: linuxserver/code-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${CODE_SERVER_PASSWORD:-password}
      - SUDO_PASSWORD=${CODE_SERVER_PASSWORD:-password}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ./workspace:/config/workspace
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - dev-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-models:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - dev-network
    restart: unless-stopped

  bolt-diy:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=production
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - DEFAULT_NUM_CTX=32768
      - RUNNING_IN_DOCKER=true
    volumes:
      - ./workspace:/app/workspace
    depends_on:
      - ollama
    networks:
      - dev-network
    restart: unless-stopped
    command: pnpm run dockerstart

networks:
  dev-network:
    driver: bridge

volumes:
  ollama-models:
